//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PracticaFinalMod1_Web
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class CodigoActividad
    {
        [Required]
        [RegularExpression("([0-9]+)")]
        public string CUIL { get; set; }
        
        
        [Required]
        [RegularExpression("([0-9]+)")]
        public string Codigo { get; set; }
    }
}
